/* This file is autogenerated by ./configure -- do not edit! */
#define POPCNT_INTRINSICS
#define HAVE_BLAS 0
#define HAVE_TLS 1
#define HAVE_PTHREAD 1
#define HAVE_GC 0
#define ARB_REENTRANT 0
#define WANT_ASSERT 0
